#!/usr/bin/env bash
# Bash script that stops 4-to_infinity_and_beyond process

# Get the paid of the progrem
id=$(pgrep "bash ./4-to_infinity_and_beyond" -f)

# Terminate the infinete process
if [- n "$id" ]
then
   kill -15 "$id"
fi
